//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int b_id { get; set; }
        public string b_title { get; set; }
        public Nullable<System.DateTime> b_date { get; set; }
        public string b_Discrip { get; set; }
        public string b_img { get; set; }
    }
}
