//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employe_Reg
    {
        public int reg_id_code { get; set; }
        public string reg_name { get; set; }
        public string reg_role { get; set; }
        public string reg_depart { get; set; }
        public string reg_client { get; set; }
        public string reg_grade { get; set; }
        public string reg_education { get; set; }
        public string reg_achieve { get; set; }
        public string reg_number { get; set; }
        public string reg_email { get; set; }
        public string reg_address { get; set; }
        public string reg_img { get; set; }
        public string password { get; set; }
        public string code { get; set; }
    }
}
