//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class starEntities : DbContext
    {
        public starEntities()
            : base("name=starEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category_T> category_T { get; set; }
        public virtual DbSet<employe_Reg> employe_Reg { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<vacancy> vacancies { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<PKG> PKGs { get; set; }
        public virtual DbSet<client> clients { get; set; }
    }
}
