//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PKG
    {
        public int P_id { get; set; }
        public string p_title { get; set; }
        public string p_price { get; set; }
        public string p_1 { get; set; }
        public string p_2 { get; set; }
        public string p_3 { get; set; }
        public string p_4 { get; set; }
        public string p_5 { get; set; }
        public string p_6 { get; set; }
    }
}
