//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public service()
        {
            this.clients = new HashSet<client>();
        }
    
        public int ser_id { get; set; }
        public string ser_title { get; set; }
        public string ser_discrip { get; set; }
        public string ser_img { get; set; }
        public Nullable<int> ser_fk_cat { get; set; }
        public string ser_img_2 { get; set; }
        public string ser_discrip_2 { get; set; }
    
        public virtual category_T category_T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client> clients { get; set; }
    }
}
