//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacancy
    {
        public int vac_id { get; set; }
        public string vac_title { get; set; }
        public string vac_discrip_1 { get; set; }
        public string vac_discrip_2 { get; set; }
        public string vac_last_date { get; set; }
        public string vac_image { get; set; }
    }
}
